### ISSUE TITLE
add h1 header

### ISSUE THREAD

**Issue by developerabrorbek** [demo-n13/online-shop#1]
Frontend papkadagi index.html faylga h1 header qo'shilsin va rangini qizil qilib qo'yilsin

**Comment by Sardorbek1712** [comment]
Bajarildi

**Comment by RavshanJaloliddinov** [comment]
men shu muommoni hal qilaman

**Comment by ABDULLOH21706** [comment]
men shu muammoni hal qilaman

**Comment by Shokirov05** [comment]
@developerabrorbek

**Comment by Abduqodir65** [comment]
@Sardorbek1712  yoge

**Comment by aabdulhodiy** [comment]
xo'p kegnchi

**Comment by developerabrorbek** [comment]
@developerabrorbek muammni men bajaraman, meni belgilab qo'yish

**Comment by TimurbekDev** [comment]
@TimurbekDev give me this issue

**Comment by Sardorbek1712** [comment]
@Abduqodir65  Qacon bog'ca borasan😂

**Comment by Abduqodiir** [comment]
@Sardorbek1712  
https://github.com/user-attachments/assets/3e294abd-d9d6-47b5-8db0-dcb50d05fe60

**Comment by Sardorbek1712** [comment]
@Abduqodir65 Xursandmisan endi sanda rasmim bor😂👍

**Comment by developerabrorbek** [comment]
Muammo hal bo'ldi

**Comment by abdulhodiy1020** [comment]
Muammo xal boldi;)
