### ISSUE TITLE
add color red to h1

### ISSUE THREAD

**Issue by developerabrorbek** [demo-n13/online-shop#4]
index html fayldagi h1 rangini red ga o'zgartirilsin

**Comment by Sardorbek1712** [comment]
Men olaman

**Comment by TimurbekDev** [comment]
@TimurbekDev  menda o'sha

**Comment by maverizes** [comment]
i will take this issue @developerabrorbek

**Comment by RavshanJaloliddinov** [comment]
men

**Comment by ZufarovAbdulla99** [comment]
men yechaman

**Comment by Abduqodiir** [comment]
> index html fayldagi h1 rangini red ga o'zgartirilsin

+

**Comment by aabdulhodiy** [comment]
xop

**Comment by Sardorbek1712** [comment]
> men yechaman

Unaqa qimang aka😂
